### ISSUE TITLE
Nunchuk.h "no such file or directory"

### ISSUE THREAD

**Issue by jkruiktech** [infusion/Fritzing#1]
Your Nunchuk library looks great, but I wonder if it supports the latest version of Arduino (v1.8.5)?

My best guess is that it's something in the header file that needs updating?

I'm using the Teensy 3.6 by the way.

![24139234_1510900932322289_1974330860_o](https://user-images.githubusercontent.com/23633247/33260490-1a127010-d3b4-11e7-8e00-077434cf37b5.png)

Help would be much appreciated :)

**Comment by infusion** [comment]
You're sure you installed the library correctly? It states that it can't find the file `nunchuk.h`.

**Comment by jkruiktech** [comment]
Worked! Sketch>Include Library>Add .ZIP Library and using the extracted wiiNunchuk subfolder worked. 
I didn't realise you could add non zipped libraries...

Thanks!

**Comment by infusion** [comment]
You're welcome :)
