### ISSUE TITLE
Nunchuck Controller Loop

### ISSUE THREAD

**Issue by jkruiktech** [infusion/Fritzing#2]
Compiles/Uploads Perfectly.

New issue: The Serial monitor shows a loop every 28 lines or so, giving 5 lines or mayhem, and repeating.

Removing the Clock and Data pins stops all Serial monitor outputs. The buttons dont change the values.

Any suggestions? 

![image](https://user-images.githubusercontent.com/23633247/33261898-8935f17a-d3b8-11e7-8a7a-38a7aeaae578.png)

Similar issue here: http://forums.trossenrobotics.com/showthread.php?7810-Being-defeated-by-a-Wii-Nunchuk

**Comment by infusion** [comment]
Please try commenting out line 24 in the nunchuk.h file:
```
#define NUNCHUK_DISABLE_ENCRYPTION
```
to
```
// #define NUNCHUK_DISABLE_ENCRYPTION
```

**Comment by jkruiktech** [comment]
Sadly that didn't change anything. 

It might be a cheap clone as you say in //line 23, but it baffles me how it could still be decrypted correctly by a Wii controller/console.

**Comment by infusion** [comment]
Hum, what nunchuk do you have? Are you sure your wiring is correct? When you use a cheap replica, disable encryption again. The Wii console probably tries both ways. When you see the stream of data, does pressing buttons and rotating the nunchuk change anything or will the numbers remain constant?

**Comment by jkruiktech** [comment]
I think it's an original (ACN 060556083) (RVL 004). 
Good point, it would try both ways. 

swapping clock and data pins also gives no output. 

The logic analyser shows a signal at this frequency (data = channel 0, clock = channel 1):
![image](https://user-images.githubusercontent.com/23633247/33302176-782e8c20-d44e-11e7-954f-958502bdcf53.png)

Zoomed in, each pulse looks like this:
![image](https://user-images.githubusercontent.com/23633247/33302202-a7fe4cc4-d44e-11e7-845a-d0c3262467be.png)

So there is a signal, it just doesnt affect the serial monitor in some way. 

Could it be that the Teensy runs jolly fast (180Mhz) or some other speed modification?

**Comment by infusion** [comment]
Okay, the original nunchuk usually works with encryption. The signals looks okay. When I had a look at teensy 1.0 it wasn't that interesting. But now the 3.6 is super cool, maybe i should get one (Update: Okay, postage is almost as high as the board itself to Germany, maybe I should wait). So I never tried the nunchuk library with teensy yet. It would be cool if we could make it work on teensy together. Do you have an arduino laying around to test it? I tried it on both, the original and the cheap china versions and it works good. That way we could remove one error source.

**Comment by jkruiktech** [comment]
Yes, the teensy 3.6 is very handy, with lots of peripherals. They're reasonably cheap for what they can do. Postage isn't great in Australia either. I got mine from Sparkfun:
https://www.sparkfun.com/products/14057

I can test it with a friends arduino, I'll see how that goes.
I'm happy to do that, I would love to get it working.

**Comment by infusion** [comment]
Please keep me in the loop as soon as you can get your hands on an Arduino :)

**Comment by jkruiktech** [comment]
I probably wont be able to test it for a week, but I'll get onto it when I can

**Comment by jkruiktech** [comment]
I will retry it soon sorry, ive been trying a PS2 controller as of late

**Comment by infusion** [comment]
Little promo tour: I wrote a HID extension for node.js, which supports PS2 controller: https://github.com/infusion/node-gamecontroller

But it would be nice if we could find the problem here as well. thx

**Comment by infusion** [comment]
@jkruiktech  Okay, we had a hard time tackling this problem with another user as well and it turns out it's a timing problem. Could you please set up the nunchuk again so that we can try the change for you as well? It would be nice to finally close this issue.
Robert

**Comment by jkruiktech** [comment]
That's good to hear. Would that timing problem be due to the clock speeds on different MCU's?

I will give it a go in the next week or so, Uni is hitting me hard at the moment!

**Comment by infusion** [comment]
It appears to have something to do with different clock speeds in combination with different Nunchuks.  We had the problem that a Nunchuk worked perfectly on an Arduino Due and printed the same output as yours on an Arduino Due. I would love to hear if the current library works for you when you comment-in line 30: #define NUNCHUK_DELAY.

Uni is a priority, so no worries.

**Comment by jkruiktech** [comment]
I'm giving it another try today. I cant find my old code anymore, so in restarting, I'm not getting the looping serial output. I'm the demo code you provided.
The Nunchuk.h file makes sense and I'm getting values printed to the serial monitor straight from the functions (nunchuck_button_Z etc.) but the values aren't changing with controller input. 

#define NUNCHUK_DELAY also doesn't change anything, although there might be something else earlier on stopping it from having any effect.

**Comment by jkruiktech** [comment]
Okay so when everything is plugged in correctly and #define NUNCHUK_DELAY is enabled, I get all the max values (and minimum values for the buttons). It sometimes takes a few tries to get this output. Otherwise I get all minimum values and buttons = 1. Should they be initialised with a zero value? 

It sounds like it's detecting the nunchuk at least but somehow the data isnt making its way to the functions which feed to the Serial.print lines?

**Comment by infusion** [comment]
Your controller definitely works? With the wii console? So, it's a progress that you, at least see some values? Could you do me a favor. In the source are multiple spots where delays could make sense but are commented out. Could you play with them by commenting in the delays again? Maybe some combination or spot will work. The NUNCHUK_DELAY enables only the delay which was the only way the other user made his nunchuk work. But maybe yours is different. It's quite certain that it is only a timing problem or an encryption problem (NUNCHUK_DISABLE_ENCRYPTION).
You don't have to initialize anything. It should work without problems right out of the box. 
BTW: What Arduino or MCU are you using?

**Comment by mindforger** [comment]
coming from a german forum with a similar issue

Arduino Due (Original) with M3 (SAM3X8E) and Adafruit Feather M4 (ATSAMD51)

lib and board file versions following shortly

--

Arduino IDE 1.8.8 (1.8.9 mentioned as still buggy)
Adafruit M4: 1.3.0 
Arduino Due 1.6.12 

i do not own those boards i am just a messenger/proxy :P

**Comment by infusion** [comment]
Hi @mindforger proxy ;D Let's continue this thread on #3
